services:
  hermes-plugin-installer:
    image: alpine:latest
    volumes:
      - grafana-plugins:/plugins
    command:
      - sh
      - -c
      - |
        apk add --no-cache curl jq bash unzip &&
        curl -fsSL https://raw.githubusercontent.com/nasa/hermes/81-deploy-plugin-figure-out-communityprivate-signing/nasa-hermes-datasource/install.sh \
          | bash -s -- /plugins

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hermes
    ports:
      - 5432:5432/tcp
    volumes:
      - timescale-data:/var/lib/postgresql/data
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000" 
    environment:
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: nasa-hermes-datasource
    depends_on:
      timescaledb:
        condition: service_started
      hermes-plugin-installer:
        condition: service_completed_successfully
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-plugins:/var/lib/grafana/plugins
      - ./config:/etc/grafana/provisioning:ro
volumes:
  timescale-data:
  grafana-data:
  grafana-plugins:
